apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: sbi
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: changeme-use-strong-password
  POSTGRES_DB: financial_data
