---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: postgres
  namespace: sbi
spec:
  hostnames:
    - db.sbi.local.julianmaze.com
  parentRefs:
    - name: default-gateway
      namespace: gateway
      sectionName: local-subdomain-postgres
  rules:
    - backendRefs:
        - name: postgres
          port: 5432
          kind: Service
