apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  labels:
    app: cloudflare-ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
        - name: ddns
          image: favonia/cloudflare-ddns:latest # https://github.com/favonia/cloudflare-ddns
          env:
            - name: DOMAINS
              value: julianmaze.com,julianmaze.link,jmaz.tv
            - name: PROXIED
              value: "false"
            - name: IP6_PROVIDER
              value: none
          envFrom:
            - secretRef:
                name: cloudflare-api-token
        # - name: ddns-anz
        #   image: favonia/cloudflare-ddns:latest
        #   env:
        #     - name: DOMAINS
        #       value: ayertonz.com,zfam.us
        #     - name: PROXIED
        #       value: "false"
        #     - name: IP6_PROVIDER
        #       value: none
        #   envFrom:
        #     - secretRef:
        #         name: cloudflare-api-token-anz
