apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
data:
  CF_API_TOKEN: dEFRMWZqWnZzR3pFVV9VdC1SOVlEWHdvYVNrNnVuZHJNTDNjWEI1RAo=
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: cloudflare-api-token-anz
# data:
#   CF_API_TOKEN:
