config:
  apiVersion: controller.config.cert-manager.io/v1alpha1
  enableGatewayAPI: true
  kind: ControllerConfiguration
crds:
  enabled: true
dns01RecursiveNameserversOnly: true
dns01RecursiveNameservers: 8.8.8.8:53
