apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: "unifi"
  name: "unifi-admin-ingress"
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-jmaze # cloudflare https issuer
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-body-size: 5000M
spec:
  rules:
    - host: "network.local.julianmaze.com"
      http:
        paths:
          - backend:
              service:
                name: "unifi"
                port:
                  number: 8443
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - network.local.julianmaze.com
      secretName: tls-unifi-ingress
