apiVersion: v1
kind: Service
metadata:
  name: unifi
spec:
  type: ClusterIP
  publishNotReadyAddresses: false
  ports:
    - name: main
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    pod.name: main
    app.kubernetes.io/name: unifi
    app.kubernetes.io/instance: unifi
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-comm
spec:
  type: LoadBalancer
  publishNotReadyAddresses: false
  ports:
    - name: main
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    pod.name: main
    app.kubernetes.io/name: unifi
    app.kubernetes.io/instance: unifi
