apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi
  labels:
    app: unifi
    app.kubernetes.io/instance: unifi
    app.kubernetes.io/name: unifi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: unifi
      app.kubernetes.io/name: unifi
      app.kubernetes.io/instance: unifi
      pod.name: main
  template:
    metadata:
      labels:
        app: unifi
        app.kubernetes.io/name: unifi
        app.kubernetes.io/instance: unifi
        pod.name: main
    spec:
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      containers:
        - name: unifi
          image: lscr.io/linuxserver/unifi-network-application:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: PST8PDT
            - name: MONGO_USER
              value: unifi
            - name: MONGO_HOST
              value: unifidb-mongodb.unifi.svc.cluster.local
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DBNAME
              value: unifi
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: unifidb-mongodb
                  key: mongodb-passwords
          ports:
            - name: web
              containerPort: 8443
              protocol: TCP
            - name: comm
              containerPort: 8080
              protocol: TCP
            - name: stun
              containerPort: 3478
              protocol: UDP
            - name: speedtest
              containerPort: 6789
              protocol: TCP
            - name: websecure
              containerPort: 8843
              protocol: TCP
            - name: portal
              containerPort: 8880
              protocol: TCP
            - name: l2-nw-discov
              containerPort: 1900
              protocol: UDP
            - name: dev-discov
              containerPort: 10001
              protocol: UDP
            - name: syslog
              containerPort: 5514
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: false
          securityContext:
            #   runAsNonRoot: true
            runAsUser: 0
            runAsGroup: 0
          #   readOnlyRootFilesystem: true
          #   allowPrivilegeEscalation: false
          #   privileged: false
          #   seccompProfile:
          #     type: RuntimeDefault
          #   capabilities:
          #     add: []
          #     drop:
          #       - ALL
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: unifi-app
