---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "synology-media"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "8000Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "ds1522-media"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "52000Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/media"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "ds1522-media-uhd"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "52000Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/media-uhd"
