---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: byparr
  labels:
    app: byparr
    app.kubernetes.io/instance: byparr
    app.kubernetes.io/name: byparr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: byparr
      app.kubernetes.io/name: byparr
      app.kubernetes.io/instance: byparr
      pod.name: main
  template:
    metadata:
      labels:
        app: byparr
        app.kubernetes.io/name: byparr
        app.kubernetes.io/instance: byparr
        pod.name: main
    spec:
      restartPolicy: Always
      dnsPolicy: None
      # We want byparr to use a public DNS server. Cluster DNS points to NextDNS.
      dnsConfig:
        nameservers:
          - 10.43.25.5 # CoreDNS External Google Service Cluster IP
      containers:
        - name: byparr
          image: ghcr.io/thephaseless/byparr:latest
          imagePullPolicy: Always
          ports:
            - name: main
              containerPort: 8191
              protocol: TCP
          resources:
            requests:
              memory: "2048Mi"
              cpu: "1500m"
