---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: byparr
spec:
  hostnames:
    - byparr.media.jmaz.tv
  parentRefs:
    - name: default-gateway
      namespace: gateway
      sectionName: media # name of the gateway listener
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: byparr
          port: 8191
          kind: Service
