apiVersion: v1
kind: Service
metadata:
  name: byparr
spec:
  type: ClusterIP
  publishNotReadyAddresses: false
  ports:
    - name: main
      port: 8191
      protocol: TCP
      targetPort: 8191
  selector:
    pod.name: main
    app.kubernetes.io/name: byparr
    app.kubernetes.io/instance: byparr
