apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
  namespace: gateway # custom namespace for gateways
spec:
  parentRefs:
    - name: default-gateway
      sectionName: https-redirect # name of the gateway listener
  hostnames:
    - "*.julianmaze.com"
    - "*.jmaz.tv"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
