---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: surfcam-julianmaze-com
  namespace: gateway # custom namespace for gateways
spec:
  parentRefs:
    - name: default-gateway
      sectionName: surfcam-redirect
  hostnames:
    - surfcam.julianmaze.com
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            hostname: www.youtube.com
            path:
              type: ReplaceFullPath
              replaceFullPath: "watch?v=MTAJsEDEapI"
            statusCode: 301
