apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: jmaze-k8s
  namespace: metallb-system
spec:
  addresses:
    - 10.50.25.192/27
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - jmaze-k8s
