---
apiVersion: v1
kind: Secret
metadata:
  name: git-private-key
data:
  ssh-privatekey: >-
    <SSH_PRIVATE_KEY_Base64>
  ssh-publickey: >-
    <SSH_PUBLIC_KEY_Base64>
---
apiVersion: v1
kind: Secret
metadata:
  name: code-server
stringData:
  # Password for code-server login
  PASSWORD: <PASSWORD>
  # Alternatively, you can use a hashed password (bcrypt)
  # HASHED_PASSWORD: <HASHED_PASSWORD>
  SUDO_PASSWORD: <SUDO_PASSWORD>
