apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-jmaze
  namespace: cert-manager
spec:
  acme:
    email: jmmaze@outlook.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-cloudflare-prod
    solvers:
      - dns01:
          cloudflare:
            email: jmmaze@outlook.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
        selector:
          dnsZones:
            - "julianmaze.com"
            - "local.julianmaze.com"
    # - http01:
    #     ingress:
    #       class: nginx
