provider:
  name: aws
env:
  - name: AWS_SHARED_CREDENTIALS_FILE
    value: /.aws/credentials/credentials # File named credentials
  - name: AWS_DEFAULT_REGION
    value: us-west-2
extraVolumes:
  - name: aws-credentials
    secret:
      secretName: external-dns
extraVolumeMounts:
  - name: aws-credentials
    mountPath: /.aws/credentials
    readOnly: true
sources:
  - gateway-httproute
  - gateway-tlsroute
extraArgs:
  [
    "--annotation-filter=external-dns.alpha.kubernetes.io/controller in (dns-controller)",
  ]
