---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: code-julianmaze-com
spec:
  hostnames:
    - code.julianmaze.com
  parentRefs:
    - name: default-gateway
      namespace: gateway
      sectionName: code-legacy-passthrough # name of the gateway listener
  rules:
    - name: code-julianmaze-com
      backendRefs:
        - name: jmaze-k8s-default-ingress
          port: 443
          kind: Service
