---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: overseerr-jmaz-tv
spec:
  hostnames:
    - overseerr.jmaz.tv
  parentRefs:
    - name: default-gateway
      namespace: gateway
      sectionName: overseerr-legacy-passthrough # name of the gateway listener
  rules:
    - name: overseerr-jmaz-tv
      backendRefs:
        - name: jmaze-k8s-default-ingress
          port: 443
          kind: Service
