---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: storage-jmaz-tv
spec:
  hostnames:
    - storage.jmaz.tv
  parentRefs:
    - name: default-gateway
      namespace: gateway
      sectionName: storage-jmaz-tv # name of the gateway listener
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ds-1522
          port: 5000
          kind: Service
