---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: surfcam-julianmaze-com
spec:
  hostnames:
    - surfcam.julianmaze.com
  parentRefs:
    - name: default-gateway
      namespace: gateway
      sectionName: surfcam-legacy-passthrough # name of the gateway listener
  rules:
    - name: surfcam-julianmaze-com
      backendRefs:
        - name: jmaze-k8s-default-ingress
          port: 443
          kind: Service
