---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: utility-pod
  namespace: development
  labels:
    app: utility-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utility-pod
  template:
    metadata:
      labels:
        app: utility-pod
        # egress-gateway: "true"
        # egress-gateway-policy: "cyberghost-vpn"
    spec:
      containers:
        - name: ubuntu
          image: ubuntu:latest
          command: ["tail"]
          args: ["-f", "/dev/null"]
          # volumeMounts:
          #   - name: ds1522-media
          #     mountPath: /mnt/ds1522-media
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      # volumes:
      #   - name: ds1522-media
      #     persistentVolumeClaim:
      #       claimName: ds1522-media
