apiVersion: v1
kind: Service
metadata:
  name: cleanuparr
spec:
  type: ClusterIP
  publishNotReadyAddresses: false
  ports:
    - name: main
      port: 11011
      protocol: TCP
      targetPort: 11011
  selector:
    pod.name: main
    app.kubernetes.io/name: cleanuparr
    app.kubernetes.io/instance: cleanuparr
