apiVersion: v1
kind: Secret
metadata:
  name: k3s-etcd-snapshot-s3-config
  namespace: kube-system
type: etcd.k3s.cattle.io/s3-config-secret
stringData:
  # etcd-s3-endpoint: ""
  # etcd-s3-endpoint-ca: ""
  # etcd-s3-endpoint-ca-name: ""
  etcd-s3-skip-ssl-verify: "false"
  etcd-s3-access-key: ""
  etcd-s3-secret-key: ""
  etcd-s3-bucket: ""
  etcd-s3-folder: "snapshots"
  etcd-s3-region: "us-west-2"
  etcd-s3-insecure: "false"
  etcd-s3-timeout: "5m"
  # etcd-s3-proxy: ""
