apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: "surfcam"
  name: "surfcam-ingress"
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-jmaze # cloudflare https issuer
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "surfcam.julianmaze.com"
      http:
        paths:
          - backend:
              service:
                name: "surfcam-nginx"
                port:
                  number: 80
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - surfcam.julianmaze.com
      secretName: tls-surfcam-ingress
