---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "jmaze-k8s-surfcam"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "1Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/jmaze-k8s/surfcam/www"
