---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: requestrr
spec:
  hostnames:
    - requestrr.media.jmaz.tv
  parentRefs:
    - name: default-gateway
      namespace: gateway
      sectionName: media # name of the gateway listener
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: requestrr
          port: 4545
          kind: Service
