apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cloudflare-jmaze
  name: external-services-ingress-jmaztv
  namespace: external-services
spec:
  rules:
    - host: storage.jmaz.tv
      http:
        paths:
          - backend:
              service:
                name: jmaztv-storage
                port:
                  number: 5000
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - storage.jmaz.tv
      secretName: tls-external-services-ingress-jmaztv
