apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cloudflare-jmaze
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-body-size: 5000M
    nginx.org/mergeable-ingress-type: minion
  name: external-services-ingress-jmaztv
  namespace: external-services
spec:
  rules:
    - host: storage.jmaz.tv
      http:
        paths:
          - backend:
              service:
                name: jmaztv-storage
                port:
                  number: 5001
            pathType: ImplementationSpecific
    - host: photos.jmaz.tv
      http:
        paths:
          - backend:
              service:
                name: jmaz-photos
                port:
                  number: 5443
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - storage.jmaz.tv
        - photos.jmaz.tv
      secretName: tls-external-services-ingress-jmaztv
