apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cloudflare-jmaze
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  name: external-services-ingress-https
  namespace: external-services
spec:
  rules:
    - host: scrypted-home.julianmaze.com
      http:
        paths:
          - backend:
              service:
                name: home-assistant-scrypted
                port:
                  number: 10443
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - scrypted-home.julianmaze.com
      secretName: tls-external-services-ingress-https
