apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cloudflare-anz
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  name: external-services-ingress-anz-https
  namespace: external-services
spec:
  rules:
    - host: photos.ayertonz.com
      http:
        paths:
          - backend:
              service:
                name: anz-photos
                port:
                  number: 5443
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - photos.ayertonz.com
      secretName: tls-external-services-ingress-anz-https
