apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cloudflare-anz
  name: external-services-ingress-anz
  namespace: external-services
spec:
  rules:
    - host: request.ayertonz.com
      http:
        paths:
          - backend:
              service:
                name: anz-request
                port:
                  number: 3579
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - request.ayertonz.com
      secretName: tls-external-services-ingress-anz
