apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cloudflare-jmaze
  name: external-services-ingress
  namespace: external-services
spec:
  rules:
    - host: home.julianmaze.com
      http:
        paths:
          - backend:
              service:
                name: home-assistant
                port:
                  number: 8123
            pathType: ImplementationSpecific
    - host: tautulli.julianmaze.com
      http:
        paths:
          - backend:
              service:
                name: tautulli
                port:
                  number: 8181
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - home.julianmaze.com
        - tautulli.julianmaze.com
      secretName: tls-external-services-ingress
