---
kind: Service
apiVersion: v1
metadata:
  name: jmaztv-storage
  namespace: external-services
spec:
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
---
kind: Endpoints
apiVersion: v1
metadata:
  name: jmaztv-storage
  namespace: external-services
subsets:
  - addresses:
      - ip: 10.0.10.250
    ports:
      - port: 5001
---
kind: Service
apiVersion: v1
metadata:
  name: jmaz-photos
  namespace: external-services
spec:
  ports:
    - protocol: TCP
      port: 5443
      targetPort: 5443
---
kind: Endpoints
apiVersion: v1
metadata:
  name: jmaz-photos
  namespace: external-services
subsets:
  - addresses:
      - ip: 10.0.10.250
    ports:
      - port: 5443
