apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "code-server-ingress"
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-jmaze # cloudflare https issuer
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "code.julianmaze.com"
      http:
        paths:
          - backend:
              service:
                name: "code-server"
                port:
                  number: 8443
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - code.julianmaze.com
      secretName: tls-code-server-ingress
