# Overload values for persistence
persistence:
  config:
    enabled: true
    existingClaim: prowlarr

# Disabling metrics - we do not have a Prometheus instance set up yet.
metrics:
  main:
    enabled: false

# Overload DNS settings to use custom DNS with cluster resolution
workload:
  main:
    podSpec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.25.5 # CoreDNS External Google Service Cluster IP
        searches:
          - cluster.local
        options:
          - name: ndots
            value: "5"
          - name: timeout
            value: "2"
          - name: attempts
            value: "2"
