# Overload values for persistence
persistence:
  config:
    enabled: true
    existingClaim: prowlarr

# Disabling metrics - we do not have a Prometheus instance set up yet.
metrics:
  main:
    enabled: false

# Overload DNS settings to use a public DNS server
workload:
  main:
    podSpec:
      dnsConfig:
        nameservers:
          - 8.8.8.8
        searches:
          - "svc.cluster.local" # Required when dnsPolicy is None
          - "cluster.local"
        options:
          - name: ndots
            value: "2"
      dnsPolicy: None
