---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: overseerr
spec:
  hostnames:
    - overseerr.jmaz.tv
  parentRefs:
    - name: default-gateway
      namespace: gateway
      sectionName: overseerr # name of the gateway listener
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: overseerr
          port: 5055
          kind: Service
