apiVersion: v1
kind: Service
metadata:
  name: overseerr
spec:
  type: ClusterIP
  publishNotReadyAddresses: false
  ports:
    - name: main
      port: 5055
      protocol: TCP
      targetPort: 5055
  selector:
    pod.name: main
    app.kubernetes.io/name: overseerr
    app.kubernetes.io/instance: overseerr
