apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: "media"
  name: "media-ingress"
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-jmaze # cloudflare https issuer
    kubernetes.io/ingress.class: nginx
    nginx.org/mergeable-ingress-type: master
spec:
  rules:
    - host: "media.jmaz.tv"
      http:
        paths:
          - backend:
              service:
                name: "radarr-ds1522"
                port:
                  number: 7878
            path: "/radarr"
            pathType: Prefix
          - backend:
              service:
                name: "sonarr-ds1522"
                port:
                  number: 8989
            path: "/sonarr"
            pathType: Prefix
          - backend:
              service:
                name: "transmission-transmission-openvpn"
                port:
                  number: 80
            path: "/transmission"
            pathType: Prefix
          - backend:
              service:
                name: "jackett"
                port:
                  number: 9117
            path: "/jackett"
            pathType: Prefix
          - backend:
              service:
                name: "radarr-ds1522-uhd"
                port:
                  number: 7878
            path: "/radarr-uhd"
            pathType: Prefix
          - backend:
              service:
                name: "sonarr-ds1522-uhd"
                port:
                  number: 8989
            path: "/sonarr-uhd"
            pathType: Prefix
  tls:
    - hosts:
        - media.jmaz.tv
      secretName: tls-jmaz-media-ingress
