apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2023-02-16T06:14:55Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2023-02-16T06:14:55Z"},{"Type":"ResourceQuotaValidated","Status":"True","Message":"","LastUpdateTime":"2023-02-16T06:16:00Z"}]}'
    field.cattle.io/projectId: local:p-cs8rq
    field.cattle.io/resourceQuota: '{"limit":{}}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"name":"media"},"name":"media"}}
    lifecycle.cattle.io/create.namespace-auth: "true"
  creationTimestamp: "2023-02-16T06:14:54Z"
  finalizers:
    - controller.cattle.io/namespace-auth
  labels:
    field.cattle.io/projectId: p-cs8rq
    kubernetes.io/metadata.name: media
    name: media
  name: media
  resourceVersion: "1865530"
  uid: 279a84f0-dcdb-4af7-802c-86612119fdbb
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
