---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "jmaze-k8s-media"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "200Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/jmaze-k8s/media"
