apiVersion: v1
kind: Secret
metadata:
  name: coredns-tls-cert
data:
  server.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdEekNDQS9lZ0F3SUJBZ0lVQUsvSFovYlNI
    b3NEZlZqcUFQZ0FFLzJpWUl3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2daWXhDekFKQmdOVkJBWVRB
    bFZUTVFzd0NRWURWUVFJREFKRFFURVNNQkFHQTFVRUJ3d0pVMkZ1SUVScApaV2R2TVJNd0VRWURW
    UVFLREFwcWRXeHBZVzV0WVhwbE1Rc3dDUVlEVlFRTERBSkpWREVoTUI4R0ExVUVBd3dZClpHNXpM
    bXh2WTJGc0xtcDFiR2xoYm0xaGVtVXVZMjl0TVNFd0h3WUpLb1pJaHZjTkFRa0JGaEpxYlcxaGVt
    VkEKYjNWMGJHOXZheTVqYjIwd0hoY05Nak14TURJek1EVXdOekV3V2hjTk1qUXhNREl5TURVd056
    RXdXakNCbGpFTApNQWtHQTFVRUJoTUNWVk14Q3pBSkJnTlZCQWdNQWtOQk1SSXdFQVlEVlFRSERB
    bFRZVzRnUkdsbFoyOHhFekFSCkJnTlZCQW9NQ21wMWJHbGhibTFoZW1VeEN6QUpCZ05WQkFzTUFr
    bFVNU0V3SHdZRFZRUUREQmhrYm5NdWJHOWoKWVd3dWFuVnNhV0Z1YldGNlpTNWpiMjB4SVRBZkJn
    a3Foa2lHOXcwQkNRRVdFbXB0YldGNlpVQnZkWFJzYjI5cgpMbU52YlRDQ0FpSXdEUVlKS29aSWh2
    Y05BUUVCQlFBRGdnSVBBRENDQWdvQ2dnSUJBSzREQmJsbFJ0aWxPZ1JoCkxSbUFCRGRvWjBBZW83
    QnZaZjZuRndxdTZSTlZyR2phQXJmYmtlMkg3TG1kZTFtZHkzdE1RaFBSSjJxYmVBYmEKYVMxb3N1
    K3Rac3ZobXdoSGcrcDBPV2paMlNmNmZiUnhaeFRTZ2FMdEVuWDUrZ1VOZEM0cmJuTFhaU0tXaDJr
    SwpMNGlhWlN4N0FNZmlhRUxTN1JPTnYyNHQyRUh3TXBxZ0Y5Ym9mdktGRkNhNWY4ZXhXN3ZFZGw0
    cmZmb0JWNUhTCkJONWVhSm03YkxSOWJ1d2RqUlJBK0JVenNCM0hXd1FqeUZzdHVLak5IVVJWbFNL
    Z2NIdTRRVCsvM21tSk8yY2sKaW1QdkJWVjhnQVhNby9tOTRZcVRwTllFOXh5L2NOTVREV2U2Nnhl
    UlI5elgxYk1mbWwwcFdEdW93QmdVdnlCagpheDkraUxuK1hFRlpJbStCV2hWdjcrejBGamFnTnZB
    MG1EK09XdnFIdENBMC91d0RHK3p3bzZadHAxTktZbTduCnhlTXNrNHNjRG9JVlFnMmpURjNFbDcw
    cTRmZVB6eUhmK016MnkrUTIwYlhJbk5sU2tvaGE1WHZlMXZ6dTFNOWoKazE1UnVaWDFNMWFXRHNl
    Rk1PYVhjTkNxS2ozaDNSSDhRVjh4V3VlQUczUkF5dEtNUkdqM3FHd1ZCenEvZmgyYQpHdFNZaGs1
    ckU4a1V3SnUxU1pQMUdQSitFeGticHp6YkE5L0QwdUZiL0NQQ2tqM0pmUmNXZjUyV0ovelp3YXBZ
    CnZkZVcxWktLZXNZTUxpUG1qclZ4Z0hOVnpIc1lIQzc5dmc5RUQ2TTdWenFHcEx3MG8zR29VNUNo
    VzI0VWYxK0MKN0V1Ymg1MmRhUFBsVkNiUXFEZUJDMUxiZDNOREFnTUJBQUdqVXpCUk1CMEdBMVVk
    RGdRV0JCUjE1RnB5aGc4SQpoT2xQUzRFdUQ0R25ETDluNERBZkJnTlZIU01FR0RBV2dCUjE1RnB5
    aGc4SWhPbFBTNEV1RDRHbkRMOW40REFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIz
    RFFFQkN3VUFBNElDQVFCNVFBSDljeG41cHA1TThUV2kKam9CdGhmam0reFlFandENlZsSTBzVy9H
    cExJaG5BQi9qR0xkeTMreGhkSVFqL3gzd29yUXpuZDVwZVZKNDNBeAppZGlLaVIzWVRrbFFmN05j
    NFI4dG0xWi92RE9sZUwvL094OHZFNkpuZHkvTDdtVy9CNVFJK3plWDRUMEUzOGNFCnFVZTZ4MTgw
    V3dtSFhVZ1AwOGdFcExLNVREL1dWK2s4NC9OMzZidG5RNzJWZnVCczNJczUwMmhlNE1KWm5vakIK
    K2xiWXBGQ2lXUDdnU1ZiVVhsaGpvUGI0aStER2xWdUJxTmtqYUlwWXdoRjRUcWVGZFRFcFF5RXlS
    Rmo1bXVIUApnWWpqZnp4SDNobHduUUpqMHBLVE5DU1JINmM4VkkxL3NhQ0QxVDZSU0Y2d2xFSTg5
    d2lwYktwWXZocVdZZndwCjlmWnkwUjN4Z0crYVIreEQ4NUdpeEoxdU5uZzdSNnE2eUhOZlBhaHNs
    aDhsSnVNVllSdzNPbzUyckp1Y0RzbWoKald6MGFYSGJucmRLYzBKTmExR1F0OEs5M05WMHJOSjlZ
    M1N4QmRIYkhydzJhaHgwSHpwaWJ2SkVnb2J1akNIcAo2TFhWTEh4c0lLU0F1b3hMc212cVd2dnIy
    WWIzQndFZ3ZjMEpwd2xqeVB2M1Rtbm5ySERBa1JXNDF6djJJUnBuCmcwVjNYTWFTczBsWklpanZx
    cGF2MmVGZUpvTS9wSFpHdEVmTTdXbktHcTE1RjRYSDdaWmhYbHlxOVZCMEJhenQKNEJFY1ZvWGxi
    U1o2bHRyRjZPbmFKbWNBMDhFbDdKc2d6dGgxR0UvSG1PcDVHY3hLTmR2dUgxeE51OTFDM3NCNQpF
    ZDErcVRiVGNwWDV5ckhvaEhMYXMwY0FqZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  server.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQ1N3d2dna29BZ0VBQW9JQ0FRQ3VBd1c1WlViWXBUb0UKWVMwWmdBUTNhR2RBSHFPd2IyWCtw
    eGNLcnVrVFZheG8yZ0szMjVIdGgreTVuWHRabmN0N1RFSVQwU2RxbTNnRwoybWt0YUxMdnJXYkw0
    WnNJUjRQcWREbG8yZGtuK24yMGNXY1Uwb0dpN1JKMStmb0ZEWFF1SzI1eTEyVWlsb2RwCkNpK0lt
    bVVzZXdESDRtaEMwdTBUamI5dUxkaEI4REthb0JmVzZIN3loUlFtdVgvSHNWdTd4SFplSzMzNkFW
    ZVIKMGdUZVhtaVp1MnkwZlc3c0hZMFVRUGdWTTdBZHgxc0VJOGhiTGJpb3pSMUVWWlVpb0hCN3VF
    RS92OTVwaVR0bgpKSXBqN3dWVmZJQUZ6S1A1dmVHS2s2VFdCUGNjdjNEVEV3MW51dXNYa1VmYzE5
    V3pINXBkS1ZnN3FNQVlGTDhnClkyc2Zmb2k1L2x4QldTSnZnVm9WYisvczlCWTJvRGJ3TkpnL2ps
    cjZoN1FnTlA3c0F4dnM4S09tYmFkVFNtSnUKNThYakxKT0xIQTZDRlVJTm8weGR4SmU5S3VIM2o4
    OGgzL2pNOXN2a050RzF5SnpaVXBLSVd1VjczdGI4N3RUUApZNU5lVWJtVjlUTldsZzdIaFREbWwz
    RFFxaW85NGQwUi9FRmZNVnJuZ0J0MFFNclNqRVJvOTZoc0ZRYzZ2MzRkCm1oclVtSVpPYXhQSkZN
    Q2J0VW1UOVJqeWZoTVpHNmM4MndQZnc5TGhXL3dqd3BJOXlYMFhGbitkbGlmODJjR3EKV0wzWGx0
    V1NpbnJHREM0ajVvNjFjWUJ6VmN4N0dCd3UvYjRQUkErak8xYzZocVM4TktOeHFGT1FvVnR1Rkg5
    ZgpndXhMbTRlZG5Xano1VlFtMEtnM2dRdFMyM2R6UXdJREFRQUJBb0lDQUVPUGp0aGxkdlZFYVZz
    cjg1dXo5VzhoCnpQeTdLS2luQjcyd1dDVGd0a080ZnNFUzYvMUFkYzc0ZURPMDdpQmtRSTIxbE80
    bXhad0Jrcjl1YTJtaS9kNUsKdjkrbXowK09uS3daeGZSc3FJQjZJL1k4RlY2alFJdm1hY1YrY2RF
    bVlSWlA3SWtRRWdjMDFJdzIxUysvYWtxegoweURJU2R5d0VqWUdVZTNRUk9lTS84akRJWjVpRkcv
    S3RZRTNnbUlnL1ZIUXZIaGhnSDdocUlOSVBIV3R5QVR3CkhRdVNxODlteGRDNFRObkdnTGwvSGxw
    a0hqVXdja0t2cUk1UWdCKzZsUkdqLzBsbUVFOS9aWjN0TlFJSjJsTlAKakZFMEcvSXFBL2lPekcv
    LzY0V3cybmhKTEdvNnkyNFNEUW0wanhjRnpTUWdtazVIZlpXYjhIejl2S2kwc3hhSApRVUtJRE13
    L2ZnL1Y5VDRyZ3Bnekx5M0pKRDNhVjNYdzZiSU1nbkorVXBZVmp0Q2VnRW1HR080aEpoek41TEhC
    Ck9wellLL2FKa2lvcW0rOHZqRTU1cmJtVklyNGtpSnFpeDlKRGo4UEhhd2FkdnRFdUpjblFEZ1ho
    YlEwbjhQOGsKWmJRYSttY2xpZXk3S2lFYlFtM09CNDR6WlZ0UDIzSmtnVDQvNXNQNGtHeWN2V295
    dDJ6SElaQi9mVkN0SEIxRQo5eUlmNWxPVUVGb0lzL2pLVUh4Unl4UVdmV3dRdFZwRHRZMVRORUkv
    RE1oU0tGRzY3L3I2NnJCMWVUNkFsNElGCi8zc3luMUJIKzR0cWxKanA1aVJCM2RVcmtCUmtoWEx0
    Q09TcTI3NSs5cUhpTThkbGk5S1JIR3NvU0ovblYvVHAKNUtJRzZuUmVXcy9yeG9EN3ozZWhBb0lC
    QVFERER4SnhoZWptWDdCYmR4MmgwR1gxSUpFZkdkN0tJNzZmTDNLYQo5M1IwQTNlN2lnK0JnMmlx
    ZzlxZVhHZHM4VnExdGhLc2YrQXgrdXJrak1JUjdDYlU1S3JFNWs1cm9MaHYwUHVrClJwZjEwMWQr
    ekRsc2pGcHhtamQwc3pnamlzQXduZFo0RVlsZkhFQ1BmSTd4c0FsdEVJYnc5RHRadUlRSE1VeDcK
    N0U5bVFxeGpKaG9TazhUb1lERitHMGZvRWFzRGMycXBoVUJFY1cxdEVnczRwSVhvQkxhS0JmNWlC
    bzBSb3REQQpQSTZqNStrL1JWeGNwb2pzK1doTmtDL2ROZ0pYYm1CdW9jaktDc0ZxTVUweUIzSlFJ
    OE02U0VzUFVyZUc2cVZvCkJwY2hIellXTmNabCtrRVppVVZnYytCM3NDVmFqU3V4aERVTWVKcUlB
    MFd0TXcwVEFvSUJBUURrWUpmR3p6MW8KeC9USG9zcnlobjFXQWl0ZUhQSzViL2IxQWUxR2NDYWNk
    S1JVMEI5NTNvNXBqbG5wbkF6T2llK01RdWR5dXhabAoxT01kOU8zc1E4SE14YUV1a1NpUGJVeTVG
    WUNoUU1NRDloS2ptaTVPQ3RsU24xL1VOR3h2azg0MzM2Smd0VWFaCnV1d3ZXQkYrcHVLQlp0WEVY
    Y042Q2tGRUJKNDIrRW9tYWxGdUFYTmhYQU51bWNRT2F2cDFxL3JGNGhOazhITG8KczJNT3FYNHVu
    R3FOZzl3MTgvSFhJbWtsWmFOeTF3Mk9LbWl0ZFZCQXlGcFo0dHJ5cEl1V0c3Qk1kNS9MOGE0cgoz
    QzcyMGJidWNqM1A2RlZMSTViZGo4MldiS0F3YVUrM281THhBUmNZRlcwSjhUTWhBNFRUYW9jUDhk
    M1dnS1F5CjJCeFJaR2N1dWJjUkFvSUJBSE84cjY3WVM5YlZsQ2pSUnEzS241U1EzRXJkNk1sNzZC
    RS83L3B2TlpQWXN1UisKQ0xGS0xZSnZkZnBjemFsZ2svZ1pybjdYNlVqK252MDVYN1dPcjRQR29t
    VHVXajJXUVpsbklNamFjalFVVUdnVgorVVNsQ3MwNU9ncHVoTExpRXlORnBBbmVMZXBYTXg5d1Fz
    aTVNUDZidmRXZXROQ0pvUjA3YlN4aWpNSWFjWHJyCkVyRlBLSmpRNnN6dWx2M2w3ZGpBVk50OUN5
    TVJRbUpqUUhFOWZZNnJyVHU4VHJJUFBRam4ySUVYN1hMbm1naEcKdVlUbjgzcllpY0RyK3RxQXYy
    YnRRUjZqdENYZHQrR3dteU5DTTl2RlBJT0tmYTc3MzVXWUNNanVrQ0hCQ1RDbwplNjNxalZIL2ww
    Q2h3T0NEamNacTJUQWRSL1M4WXNTdFhGeG1YQzBDZ2dFQVRGUThaaVk5MEJlRXFIU3dmLzZUClJY
    dlVJdEJxRDdCc1NkY3JCcS9WTjlXRVZ4UjRjTE1CeGlYZHgwWnd3VmM0eVJoVFl2VkV0eVJBQkhN
    b1VoOFQKVnUxMndhbWlkTTJESnhrWXRNeUFZWUtOR0VFZjJOV25iUVgzY1dWVUdMYTk1YzdJNXFt
    dnZ4SEtmc2hna0lRVwprRWxlaVJNTmtteDdBOURIVUhnTDBHc1liRHZ2NUVwc216cXBYR2hFN2E5
    ZFVXWU9OVjVvQ1g1clRTczVFVHNXCklkWkFjNGZrL0pKenNod1dWUHVyZkNpUWMra1J1WlU5SFcz
    RTMvUSs4eHl0LytDN2Q5NSs2QW5mYUg4UE5RTFoKeGZOUkRwd0dnR2JmdjdidWt6K2ZkVEVtbTRa
    Undhcm5scnNXNjZIUmN4ZlhyR3lhU0djV2VpZmd6eE5QcVQ1SgpBUUtDQVFFQXBoTVhOb0JsY2pX
    Y1MvajBOWGsvcHY3VlNYaFFKbWZHZmx3cEYwMkYvcTRtSytTbTlTTGx1SmhuClpQMmRUaENUeDVL
    R3B1QTVIcXg2bktxaEVlSjdlOEp1OWtiTmtWMEhpYkV3ZVQ3eGlrcnBzUlUrSGsrbTdLQS8KWmky
    UnNjdmszS214SkY3UEMzMzVaZ1dmNzlvM1NKbWM4TFV6V1FXa2ZhcWJBS2FlUGF4eEQ3VzNaNkFJ
    MW5rZgo2ajdQbzlwWnJaZXl5dmFDdGYwdU5IZThuK3JJWmt6L2FsTkR1VTIyRElUdklaN3dnekVu
    WDkvVTE0ZVp6LzFSCjlmcERURzUyanAwSHFQcmRTUkdiSXZONGpjVzR3T3JxR1RhM2w2c2ZBR2NT
    OUtFMWptd1VRVGgvQm5wV01VL3MKeGkwbzJ6WjlabTlTRmdyaG1FeENBbXo3aWpRRW5nPT0KLS0t
    LS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
