apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: transmission
    app.kubernetes.io/name: transmission-openvpn
  name: transmission-transmission-openvpn
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: transmission
      app.kubernetes.io/name: transmission-openvpn
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: transmission
        app.kubernetes.io/name: transmission-openvpn
      namespace: media
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: transmission-transmission-openvpn
            - secretRef:
                name: transmission-transmission-openvpn
          image: haugene/transmission-openvpn:latest
          imagePullPolicy: Always
          name: transmission-openvpn
          ports:
            - containerPort: 9091
              name: http
              protocol: TCP
            - containerPort: 8118
              name: proxy
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 5
          resources: {}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: data
            # - mountPath: /etc/openvpn/custom/
            #   name: data
            #   subPath: cyberghost
            - mountPath: /config
              name: data
            - mountPath: /media
              name: ds1522-media
            - mountPath: /media-uhd
              name: ds1522-media-uhd
            - name: auth
              mountPath: /etc/openvpn/custom
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: transmission-transmission-openvpn
      serviceAccountName: transmission-transmission-openvpn
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: transmission
        - name: ds1522-media
          persistentVolumeClaim:
            claimName: ds1522-media
        - name: ds1522-media-uhd
          persistentVolumeClaim:
            claimName: ds1522-media-uhd
        - name: auth
          secret:
            secretName: transmission-auth
            defaultMode: 0777