# -- Number of replicas to run. Chart is not designed to scale horizontally, use at your own risk
replicaCount: 1

# -- Use host network
hostNetwork: false

hostPort:
  # -- Use host port for the application
  enabled: false
  # -- Host port to bind to
  port: 9091

# -- Common labels for all resources of the chart
commonLabels: {}

# -- Additional port definitions for the pod
additionalPorts:
  - name: proxy
    protocol: TCP
    containerPort: 8118

# -- Additional port definitions for the service
additionalServicePorts:
  - port: 8118
    targetPort: 8118
    protocol: TCP
    name: http-proxy

image:
  # -- Image repository
  repository: haugene/transmission-openvpn
  # -- Image pull policy
  pullPolicy: Always
  # -- Image tag (if not specified, defaults to the chart's appVersion)
  tag: latest

# -- Image pull secrets
imagePullSecrets: []
# -- String to partially override fullname template with a string (will prepend the release name)
nameOverride: ""
# -- String to fully override fullname template with a string
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Annotations for the pods
podAnnotations: {}

# -- Security context for the pods
podSecurityContext: {}

# -- Security context for the container. NET_ADMIN capability is required for the VPN to work properly.
securityContext:
  capabilities:
    add:
      - NET_ADMIN

# -- Deployment strategy
strategy:
  type: Recreate

service:
  # -- Type of the service
  type: ClusterIP
  # -- Port for the service to use
  port: 80
  # -- Service annotations
  annotations: {}
  # -- clusterIP for the service
  clusterIP: "10.43.184.230"
  # -- loadBalancerIP for the service
  loadBalancerIP: ""
  # -- externalName for the service
  externalName: ""
  # -- loadBalancerClass for the service
  loadBalancerClass: ""

ingress:
  # -- Expose the app using an ingress
  enabled: false
  # -- Ingress class name
  className: ""
  # -- Annotations for the ingress
  annotations: {}
  # -- Ingress hosts configuration
  # @default -- see [values.yaml](values.yaml)
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  # -- The TLS configuration for the Ingress
  tls: []

# -- The resource requests and limits of the container
resources: {}

# -- The node selector for the deployment
nodeSelector: {}

# -- Tolerations for the pod assignment
tolerations: []

# -- Affinity for the pod assignment
affinity: {}

persistence:
  # -- Enable persistence
  enabled: true
  # -- Persistence type is pvc. When `false`, data volume definition is read from `persistence.dataVolume`
  isPvc: true
  # -- Name of the existing claim to be used
  existingClaim: transmission
  # -- Storage class for the data volume
  storageClass: ""
  # -- Volume name override for the pvc - default is "data"
  volumeName: ""
  # -- Annotations for the claim
  annotations:
    {}
    # helm.sh/resource-policy: keep
  # -- Access modes for the claim
  accessModes:
    - ReadWriteOnce
  # -- Size for the claim
  size: 64Gi
  # -- Alternative data volume definition (e.g. nfs, hostPath). Used when `persistence.isPvc` is `false`
  # dataVolume:
  #   # subPath:
  #   #   path: "transmission/data"
  #   hostPath:
  #     path: /path/on/host

# -- Non-sensitive environment variables to be set in the pods. See the [application docs](https://haugene.github.io/docker-transmission-openvpn/config-options/)
env:
  OPENVPN_PROVIDER: CUSTOM
  OPENVPN_USERNAME: STy4SB9bvd
  OPENVPN_PASSWORD: dQiMEE4UKL
  TRANSMISSION_DOWNLOAD_DIR: /media/Downloads/complete
  TRANSMISSION_INCOMPLETE_DIR: /media/Downloads/incomplete
  TRANSMISSION_WATCH_DIR: /media/Downloads/watch
  TRANSMISSION_SEED_QUEUE_ENABLED: "false"
  TRANSMISSION_SPEED_LIMIT_UP: "5000"
  TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "true"
  TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT: "10"
  TRANSMISSION_WEB_UI: combustion
  LOCAL_NETWORK: 0.0.0.0/0
  TRANSMISSION_DOWNLOAD_QUEUE_SIZE: "10"
  TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
  TRANSMISSION_RATIO_LIMIT: "2"
  CREATE_TUN_DEVICE: "true"
  WEBPROXY_ENABLED: "true"
  WEBPROXY_PORT: "8118"

# -- Sensitive environment variables to be set in the pods. See the [application docs](https://haugene.github.io/docker-transmission-openvpn/config-options/)
secretEnv:
  {}
  # OPENVPN_USERNAME: user
  # OPENVPN_PASSWORD: MySecretPassword1!

# -- Mount the /dev/net/tun device into the pod. Required by OpenVPN when a `tun` device is used
mountTunDevice: false

# -- DNS configuration for the pod
dnsConfig: {}

# -- DNS policy for the pod
dnsPolicy: ClusterFirst

# -- Arbitrary extra volume definitions for the pod
extraVolumes:
  - name: ds1522-media
    persistentVolumeClaim:
      claimName: ds1522-media
  - name: ds1522-media-uhd
    persistentVolumeClaim:
      claimName: ds1522-media-uhd

# -- Arbitrary extra volume mounts for the pod
extraVolumeMounts:
  - mountPath: /etc/openvpn/custom/
    name: data
    subPath: "cyberghost"
  - mountPath: /config
    name: data
  - mountPath: /media
    name: ds1522-media
  - mountPath: /media-uhd
    name: ds1522-media-uhd

# -- Pod liveness probe
livenessProbe: {}

# -- Pod readiness probe
readinessProbe:
  tcpSocket:
    port: http

# -- Init containers
initContainers:
  []
  # - name: init
  #   image: busybox:stable-musl
  #   command:
  #     - sh
  #     - -c
  #     - echo "initializing..."

# -- Sidecar containers
sidecarContainers:
  []
  # - name: sidecar
  #   image: busybox:stable-musl
  #   command:
  #     - tail
  #     - -f
  #     - /dev/null
