apiVersion: v1
kind: Service
metadata:
  name: jackett
spec:
  type: ClusterIP
  publishNotReadyAddresses: false
  ports:
    - name: main
      port: 9117
      protocol: TCP
      targetPort: 9117
  selector:
    pod.name: main
    app.kubernetes.io/name: jackett
    app.kubernetes.io/instance: jackett
