---
apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission
  namespace: media
data:
  CREATE_TUN_DEVICE: "true"
  LOCAL_NETWORK: "10.0.0.0/8"
  OPENVPN_CONFIG: cyberghost
  OPENVPN_PROVIDER: CUSTOM
  TRANSMISSION_DOWNLOAD_DIR: /media/Downloads/complete
  TRANSMISSION_INCOMPLETE_DIR: /media/Downloads/incomplete
  TRANSMISSION_RATIO_LIMIT: "2"
  TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
  TRANSMISSION_SEED_QUEUE_ENABLED: "false"
  TRANSMISSION_SPEED_LIMIT_UP: "5000"
  TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "true"
  TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT: "10"
  TRANSMISSION_WATCH_DIR: /media/Downloads/watch
  TRANSMISSION_WEB_UI: combustion
  WEBPROXY_ENABLED: "true"
  WEBPROXY_PORT: "8118"
  WEBPROXY_BIND_ADDRESS: "0.0.0.0"
