---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: transmission
    app.kubernetes.io/name: transmission-openvpn
  name: transmission-openvpn
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: transmission
      app.kubernetes.io/name: transmission-openvpn
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: transmission
        app.kubernetes.io/name: transmission-openvpn
      namespace: media
    spec:
      dnsConfig:
        nameservers:
          - 8.8.8.8
      containers:
        - envFrom:
            - configMapRef:
                name: transmission
            - secretRef:
                name: transmission
          # We want jackett to use a public DNS server. Cluster DNS points to NextDNS.
          image: haugene/transmission-openvpn:latest
          imagePullPolicy: Always
          name: transmission-openvpn
          ports:
            - containerPort: 9091
              name: http
              protocol: TCP
            - containerPort: 8118
              name: proxy
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 60
            failureThreshold: 5
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2048Mi"
              cpu: "1500m"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /config
              name: data
            - mountPath: /media
              name: ds1522-media
            - mountPath: /media-uhd
              name: ds1522-media-uhd
            - name: auth
              mountPath: /etc/openvpn/custom
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: transmission
        - name: ds1522-media
          persistentVolumeClaim:
            claimName: ds1522-media
        - name: ds1522-media-uhd
          persistentVolumeClaim:
            claimName: ds1522-media-uhd
        - name: auth
          secret:
            secretName: transmission-auth
            defaultMode: 0777
