---
apiVersion: v1
kind: Secret
metadata:
  name: transmission
  namespace: media
type: Opaque
data:
  OPENVPN_PASSWORD: <BASE64_ENCODED_PASSWORD>
  OPENVPN_USERNAME: <BASE64_ENCODED_USERNAME>

---
apiVersion: v1
kind: Secret
metadata:
  name: transmission-auth
  namespace: media
type: Opaque
data:
  auth.txt: <BASE64_ENCODED_AUTH_TXT_CONTENT>
  ca.crt: >-
    <BASE64_ENCODED_CA_CRT_CONTENT>
  client.crt: >-
    <BASE64_ENCODED_CLIENT_CRT_CONTENT>
  client.key: >-
    <BASE64_ENCODED_CLIENT_KEY_CONTENT>
  cyberghost.ovpn: >-
    <BASE64_ENCODED_CYBERGHOST_OVPN_CONTENT>
