
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


#Google Assistant
google_assistant: !include g_assistant_integration.yaml

#Sensors
binary_sensor:
  - platform: ping
    host: 8.8.8.8
    name: "Google DNS Ping"
    scan_interval: 300

#LocalTuya Devices
localtuya:
  - host: 192.168.15.84
    device_id: ebacc999eb99029c61ol13
    local_key: dec21da5fa7d6ab5
    friendly_name: Main Lamp
    protocol_version: "3.3"
    entities:
    - platform: light
      friendly_name: Main Lamp
      id: 20
      color_mode: 21
      brightness: 22
      color_temp: 23
      color: 24
      brightness_lower: 10
      brightness_upper: 1000
      color_temp_min_kelvin: 2700
      color_temp_max_kelvin: 6500
      scene: 25
  - host: 192.168.15.85
    device_id: eb3ef98d887ae1cd23673v
    local_key: 1af63a95dc28a43c
    friendly_name: Kitchen Table
    protocol_version: "3.3"
    entities:
    - platform: light
      friendly_name: Kitchen Table
      id: 20
      color_mode: 21
      brightness: 22
      color_temp: 23
      color: 24
      brightness_lower: 10
      brightness_upper: 1000
      color_temp_min_kelvin: 2700
      color_temp_max_kelvin: 6500
      scene: 25
  - host: 192.168.15.86
    device_id: eb6a8e1db0b6f40443m88q
    local_key: fa60194fc66b6e6b
    friendly_name: Entry Way
    protocol_version: "3.3"
    entities:
    - platform: light
      friendly_name: Entry Way
      id: 20
      color_mode: 21
      brightness: 22
      color_temp: 23
      color: 24
      brightness_lower: 10
      brightness_upper: 1000
      color_temp_min_kelvin: 2700
      color_temp_max_kelvin: 6500
      scene: 25