apiVersion: v1
kind: Service
metadata:
  name: requestrr
spec:
  type: ClusterIP
  publishNotReadyAddresses: false
  ports:
    - name: main
      port: 4545
      protocol: TCP
      targetPort: 4545
  selector:
    pod.name: main
    app.kubernetes.io/name: requestrr
    app.kubernetes.io/instance: requestrr
