apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-jmaze
    field.cattle.io/publicEndpoints: '[{"addresses":["10.50.25.192"],"port":443,"protocol":"HTTPS","serviceName":"cattle-system:rancher","ingressName":"cattle-system:rancher","hostname":"rancher.local.julianmaze.com","allNodes":false}]'
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: rancher
    meta.helm.sh/release-namespace: cattle-system
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  creationTimestamp: "2023-02-13T06:40:30Z"
  generation: 1
  labels:
    app: rancher
    app.kubernetes.io/managed-by: Helm
    chart: rancher-2.7.1
    heritage: Helm
    release: rancher
  name: rancher
  namespace: cattle-system
  resourceVersion: "1199706"
  uid: 70a7e36d-3a44-435c-88b4-f6c74213c4df
spec:
  rules:
    - host: rancher.local.julianmaze.com
      http:
        paths:
          - backend:
              service:
                name: rancher
                port:
                  number: 80
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - rancher.local.julianmaze.com
      secretName: tls-rancher-ingress
status:
  loadBalancer:
    ingress:
      - ip: 10.50.25.192
