bootstrapPassword: <PASSWORD>
hostname: rancher.local.julianmaze.com
replicas: 1
privateCA: false
ingress.enabled: true
ingress.tls.source: secret # I want this to point to the ingress
ingress.extraAnnotations:
  cert-manager.io/cluster-issuer: cloudflare-jmaze # This takes care of the TLS cert
  kubernetes.io/ingress.class: nginx # This takes care of the ip assignment
livenessProbe:
  initialDelaySeconds: 180
  periodSeconds: 90
readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 90
# As of 3/22/25 v2.10.3 is the latest stable release
# helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
# helm repo update
# helm upgrade rancher rancher-stable/rancher --namespace cattle-system -f values.yaml --version 2.10.3
# or
# helm upgrade rancher rancher-stable/rancher --namespace cattle-system --reuse-values
